version: "0.2"

metadata:
  name: "terraform"
  display_name: "Terraform"
  description: "Infrastructure as Code tool for building, changing, and versioning infrastructure"
  version: "1.6.6"
  category: "infrastructure"
  subcategory: "iac"
  tags: ["terraform", "infrastructure", "iac", "cloud", "provisioning"]
  license: "MPL-2.0"
  language: "Go"
  maintainer: "HashiCorp"
  urls:
    website: "https://www.terraform.io"
    documentation: "https://developer.hashicorp.com/terraform/docs"
    source: "https://github.com/hashicorp/terraform"
    issues: "https://github.com/hashicorp/terraform/issues"
    support: "https://support.hashicorp.com"
    download: "https://releases.hashicorp.com/terraform/"
    changelog: "https://github.com/hashicorp/terraform/blob/main/CHANGELOG.md"
    license: "https://github.com/hashicorp/terraform/blob/main/LICENSE"

packages:
  - name: "terraform"
    package_name: "terraform"
    version: "1.6.6"

files:
  - name: "binary"
    path: "/usr/local/bin/terraform"
    type: "binary"
    owner: "root"
    group: "root"
    mode: "0755"

commands:
  - name: "terraform"
    path: "/usr/local/bin/terraform"
    arguments: ["init", "plan", "apply", "destroy", "validate", "fmt", "show", "state"]
    man_page: "terraform(1)"

binaries:
  - name: "main"
    url: "https://releases.hashicorp.com/terraform/{{version}}/terraform_{{version}}_{{os}}_{{arch}}.zip"
    version: "1.6.6"
    architecture: "{{arch}}"
    platform: "{{os}}"
    checksum: "sha256:b8a3892c58c33ee2b4b8e7c2c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8"
    install_path: "/usr/local/bin"
    executable: "terraform"
    permissions: "0755"
    archive:
      format: "zip"
      strip_prefix: ""
      extract_path: "/tmp/sai-terraform-extract"
    custom_commands:
      download: "wget -O terraform_{{version}}_{{os}}_{{arch}}.zip {{url}} && echo '{{checksum}}  terraform_{{version}}_{{os}}_{{arch}}.zip' | sha256sum -c"
      extract: "unzip -o terraform_{{version}}_{{os}}_{{arch}}.zip -d {{archive.extract_path}}"
      install: "cp {{archive.extract_path}}/terraform {{install_path}}/terraform && chmod {{permissions}} {{install_path}}/terraform"
      uninstall: "rm -f {{install_path}}/terraform"
      validation: "{{install_path}}/terraform version"
      version: "{{install_path}}/terraform version | head -n1 | grep -o 'v[0-9.]*'"

providers:
  apt:
    repositories:
      - name: "hashicorp-official"
        url: "https://apt.releases.hashicorp.com"
        key: "https://apt.releases.hashicorp.com/gpg"
        type: "upstream"
        packages:
          - name: "terraform"
            package_name: "terraform"
            version: "1.6.6"
        recommended: true

  dnf:
    repositories:
      - name: "hashicorp-official"
        url: "https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo"
        type: "upstream"
        packages:
          - name: "terraform"
            package_name: "terraform"
            version: "1.6.6"
        recommended: true

  brew:
    packages:
      - name: "terraform"
        package_name: "terraform"

  binary:
    binaries:
      - name: "main"
        url: "https://releases.hashicorp.com/terraform/{{version}}/terraform_{{version}}_{{os}}_{{arch}}.zip"
        version: "1.6.6"
        architecture: "{{arch}}"
        platform: "{{os}}"
        checksum: "sha256:b8a3892c58c33ee2b4b8e7c2c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8c8"
        install_path: "/usr/local/bin"
        executable: "terraform"
        permissions: "0755"
        archive:
          format: "zip"
          strip_prefix: ""
          extract_path: "/tmp/sai-terraform-extract"
        custom_commands:
          download: "wget -O terraform_{{version}}_{{os}}_{{arch}}.zip {{url}}"
          extract: "unzip -o terraform_{{version}}_{{os}}_{{arch}}.zip -d {{archive.extract_path}}"
          install: "cp {{archive.extract_path}}/terraform {{install_path}}/terraform && chmod {{permissions}} {{install_path}}/terraform"
          uninstall: "rm -f {{install_path}}/terraform"
          validation: "{{install_path}}/terraform version"
          version: "{{install_path}}/terraform version | head -n1 | grep -o 'v[0-9.]*'"

compatibility:
  matrix:
    - provider: "apt"
      platform: ["ubuntu", "debian"]
      architecture: ["amd64", "arm64"]
      supported: true
      recommended: true
      tested: true
    - provider: "dnf"
      platform: ["fedora", "rhel", "centos", "rocky", "alma"]
      architecture: ["amd64", "arm64"]
      supported: true
      recommended: true
    - provider: "brew"
      platform: "macos"
      architecture: ["amd64", "arm64"]
      supported: true
      recommended: true
    - provider: "binary"
      platform: ["linux", "macos", "windows"]
      architecture: ["amd64", "arm64", "386"]
      supported: true
      recommended: true
      notes: "Direct binary download from HashiCorp releases"